[23기 고유영, 최혜림, 한상웅] ADD: models.py
wecode-bootcamp-korea/23-2nd-humblebug-backend pull request #1
Opened 2021-08-18 10:09 UTC by lunayyko

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-18 12:40 UTC, lordmyshepherd requested changes

2021-08-18 12:40 UTC, lordmyshepherd commented on projects/models.py
> +    def __str__(self):
Line 7에 한 줄 띄워주세요! 컨벤션은 기본적으로 맞춰주세요~

```suggestion

    def __str__(self):
```

2021-08-18 12:40 UTC, lordmyshepherd commented on projects/models.py
> +        return self.name
함수와 class 사이에 한 칸 띄워주세요~

2021-08-18 12:40 UTC, lordmyshepherd commented on my_settings.py
> +DATABASES = {
my_settings.py 파일이 그대로 올라왔네요! gitignore에 추가해주세요.
게다가 RDS 주소와 password까지 그대로 올라왔으니 RDS 지우고 새로 만들어주세요.
Github에 한번이라도 노출되면 데이터베이스 요금이 부과될 수 있으니 반드시 지우고 새로 만들어주세요.

2021-08-18 12:40 UTC, lordmyshepherd commented on projects/models.py
> +    isdelete       = models.BooleanField(default=False)
`updated_at` colum도 추가해주세요.

2021-08-18 12:40 UTC, lordmyshepherd commented on projects/models.py
> +        db_table = 'options'
마찬가지로 한칸 띄워주세요.

2021-08-18 12:40 UTC, lordmyshepherd commented on projects/models.py
> +    option  = models.ForeignKey('option', on_delete=models.SET_NULL, null=True)
대부분 중요한 데이터인 경우 생성(`created_at`)과 업데이트(`updated_at`)에 대한 정보를 저장해야 됩니다.
추가로 이런 반복적인 시간기록 요소를 작성한다면, 매번 선언하기 보다는 아래와 같이 추상화된 class를 만들고 상속 받아서 구현해 주세요.
```python
class TimeStampModel(models.Model):
    created_at  = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    class Meta:
        abstract = True
```
만약 다른 앱에 있는 모델 클래스에서도 사용하고 싶다면 core app을 생성해서 core.models.py에 클래스 선언뒤 임포트 해주세요.

2021-08-18 12:43 UTC, lordmyshepherd commented
기본적으로 pycache 파일도 굉장히 많이 올라왔습니다. `gitignore`에 제대로 추가해서 올라오지 않도록 수정해주세요!

최종적으로 PR을 만들고나서 `Filed Changed` Tab을 클릭해서 내가 작성한 코드에 이상한 점은 없는지 최종적으로 확인하는 습관을 만들어주세요!! 기능을 구현하기에 앞서 기본적인 내용을 잘 지키고 있는지 점검하시고, 특히 백엔드 개발자는 더욱 더 `double check`하는 습관을 만드시기를 바라겠습니다.

2021-08-18 12:46 UTC, lunayyko commented
초기 세팅때 my_settings.py 안 들어가게 하고 gitignore에 파이캐시도 넣고 순태님께 리뷰받았었는데 rebase하면서 커밋을 뭉치다가 conflict solve하는것 고르다가 이렇게 된 것 같습니다 ㅠㅠㅠㅠ 싹고치고 리뷰요청 드리겠습니다~!

2021-08-18 14:26 UTC, lunayyko commented on projects/models.py
> +    def __str__(self):
넵

2021-08-18 14:39 UTC, lunayyko commented on projects/models.py
> +        db_table = 'options'
넵

2021-08-19 06:06 UTC, lordmyshepherd commented
수정사항은 잘 반영 되었네요! 리베이스만 잘 해서 올려주세요! (커밋이 12개네요!)

2021-08-19 07:54 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-08-19 07:54 UTC, merged