Add:소셜로그인(카카오)기능 추가, unit test 완료.
wecode-bootcamp-korea/23-2nd-humblebug-backend pull request #2
Opened 2021-08-20 04:57 UTC by tkddnd82

- 카카오 로그인 기능 추가
- unit test 완료
- test.py 추가

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)
-
![unit_test](https://user-images.githubusercontent.com/84978912/130181406-3f9cfec3-3aff-4c35-906e-9d590a81546a.jpg)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-23 01:20 UTC, lordmyshepherd requested changes

2021-08-23 01:20 UTC, lordmyshepherd commented on users/tests.py
> +class KakaoSigninTest(TestCase):
먼저 모든 파일의 인덴트를 4칸으로 맞춰주세요!
인덴트는 팀 컨벤션에 맞추셔야 합니다!

2021-08-23 01:20 UTC, lordmyshepherd commented on users/views.py
> +			user.save()
`get_or_create()` method를 찾아서 적용해보시면 boiler plate 코드를 수정해볼 수 있을 것 같네요~

2021-08-23 06:18 UTC, lunayyko commented on users/tests.py
> +class KakaoSigninTest(TestCase):
<img width="411" alt="Screen Shot 2021-08-23 at 3 17 53 PM" src="https://user-images.githubusercontent.com/8315252/130399601-d71a889e-4137-4556-93a5-0449975ab8f5.png">

이렇게 위아래 4칸 말씀하시는 걸까요..?

2021-08-23 06:41 UTC, tkddnd82 commented on users/views.py
> +			user.save()
넵@!

2021-08-23 06:42 UTC, tkddnd82 commented on users/tests.py
> +class KakaoSigninTest(TestCase):
![인덴트1](https://user-images.githubusercontent.com/84978912/130402286-aedabf8b-eaf5-4a80-85ea-a2a9712489a5.jpg)

인덴트 4칸 이렇게 말씀하신게 맞을까요?

2021-08-23 08:08 UTC, lordmyshepherd commented
상웅님 여전히 인덴트가 8칸이네요..

2021-08-23 08:11 UTC, tkddnd82 commented
> 상웅님 여전히 인덴트가 8칸이네요..

병민님 VS에서 인덴트 4칸으로 맞춰져있는데 수정을 해도 계속 변하지가 않네요 ㅜㅜ vim상에서 변경하려니 탭 오류가 계속 발생합니다 ㅜㅜ

2021-08-24 01:09 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-08-24 01:09 UTC, lordmyshepherd commented
컨플릭트 해결해주세요~

2021-08-24 12:49 UTC, lordmyshepherd commented
LGTM :thumup

2021-08-24 12:49 UTC, merged