[23기 최혜림] project 상세 페이지 view 작성, test.py 작성
wecode-bootcamp-korea/23-2nd-humblebug-backend pull request #4
Opened 2021-08-20 12:00 UTC by rimi0108

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 프로젝트 view 작성, test.py 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 상세 페이지 project 정보 출력
- 상세 페이지 후원 옵션 출력

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-24 12:52 UTC, lordmyshepherd requested changes
LGTM

2021-08-24 12:52 UTC, lordmyshepherd commented on projects/views.py
> +        project = Project.objects.get(id=project_id)
혜림님!! 엔드포인트 정말 잘 작성해주셨네요!
리뷰할게 거의 없어요!

다만 line 49~60에 보면 몇군대서 쿼리가 여러번 수행되는 경우가 있을 것 같네요!
`prefetch_related()`를 사용해서 쿼리를 줄여보시면 어떨까요?

2021-08-25 00:55 UTC, rimi0108 commented on projects/views.py
> +        project = Project.objects.get(id=project_id)
넵 확인했습니다

2021-08-25 07:06 UTC, rimi0108 commented
병민님! user view에 import 코드들이 중복되어 제가 추가로 수정하여 PR 올렸는데 혹시 branch 따로 파서 올려야 하면 다시 올리겠습니다!

2021-08-25 09:06 UTC, lordmyshepherd commented
> 병민님! user view에 import 코드들이 중복되어 제가 추가로 수정하여 PR 올렸는데 혹시 branch 따로 파서 올려야 하면 다시 올리겠습니다!

이정도는 괜찮습니다!! 고생 많으셨어요
LGTM 👍

2021-08-25 09:06 UTC, merged