[23기 고유영] 프로젝트 업로드 WIP: 이미지 업로드
wecode-bootcamp-korea/23-2nd-humblebug-backend pull request #6
Opened 2021-08-23 09:12 UTC by lunayyko

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
-프로젝트 업로드 Create, 이미지 업로드 시도
		 
## 수정 사항들 자세한 내용
-프론트에서 받은 이미지파일을 S3에 업로드하고 URL과 프로젝트 정보를 디비에 저장하려고 함

## 기타 질문 및 특이 사항
-포스트맨에서 전달하는 값 중에 어떤 부분이 잘못되서어 데이터가 못 넘어가고 유니코드 디코드 에러가 나고있는 걸까요..?

*에러 메세지
<img width="777" alt="Screen Shot 2021-08-23 at 5 18 23 PM" src="https://user-images.githubusercontent.com/8315252/130415302-973293f7-3c98-4014-85bf-c8e80be9cbe5.png">

*포스트맨 상태
![Screen Shot 2021-08-23 at 5 18 47 PM](https://user-images.githubusercontent.com/8315252/130415362-eb0f4033-c1e4-4223-b404-3edab2eb7757.png)
![Screen Shot 2021-08-23 at 5 18 38 PM](https://user-images.githubusercontent.com/8315252/130415378-86df5214-dcdf-4c65-821f-1e6c2a83990d.png)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-24 01:39 UTC, lordmyshepherd requested changes

2021-08-24 01:39 UTC, lordmyshepherd commented on projects/models.py
> +
필요없는 코드는 지워주세요~

2021-08-24 01:39 UTC, lordmyshepherd commented on projects/views.py
> +#         return Response(serializers.errors, status= status.HTTP_400_BAD_REQUEST)
이 코드는 뭔가요??

2021-08-24 01:39 UTC, lordmyshepherd commented on projects/views.py
> +
DRF로 작성하셨네요??
유영님 DRF로 작성하신 이유가 있으신가요?

2021-08-24 01:39 UTC, lordmyshepherd commented on projects/views.py
> +                main_image_url = request.FILES.get('main_image_url')
파일데이터를 main_image_url colum에 저장하시는 건가요?

2021-08-24 01:42 UTC, lordmyshepherd requested changes

2021-08-24 01:42 UTC, lordmyshepherd commented on projects/views.py
> +                main_image_url = request.FILES.get('main_image_url')
커뮤니티 글 참고하셔서 파일 데이터는 AWS S3 저장소에 저장하고, 해당 파일이 위치한 AWS url만 데이터베이스에 저장하는 방향으로 수정해보세요~

파일 데이터는 데이터베이스에 저장하지 않습니다. 그 이유는 파일 데이터는 많은 디스크 요량을 차지하기 때문에 스토리지 저장소에 별도로 저장해야 합니다.


https://community.wecode.co.kr/t/django-s3/1163

2021-08-24 01:42 UTC, lordmyshepherd commented
컨플릭트도 해결해주세요~

2021-08-24 02:26 UTC, lunayyko commented on projects/models.py
> +
넵

2021-08-24 02:27 UTC, lunayyko commented on projects/views.py
> +#         return Response(serializers.errors, status= status.HTTP_400_BAD_REQUEST)
이미지 업로드 테스트할 때 썼던 뷰입니다~ 지우겠습니다

2021-08-24 02:28 UTC, lunayyko commented on projects/views.py
> +
참고했던 블로그에서 rest framework를 사용했길래 사용했습니다! 다른 의도는 없습니다

2021-08-25 04:09 UTC, lunayyko commented on projects/views.py
> +            bucket.Object('main_image_url').delete
게시글에서 이미지를 수정할 때 s3서버에서 이미지를 삭제하려면 어떻게 해야할까요? bucket dir에 delete가 있어서 사용해보려고 했는데 제 컴퓨터에서는 access_denied가 떠서 s3서버가 있는 상웅님 컴퓨터에서 다시 해볼 예정입니다!

2021-08-25 04:37 UTC, tkddnd82 commented on projects/views.py
> +            bucket.Object('main_image_url').delete
![s3 denied](https://user-images.githubusercontent.com/84978912/130727262-3c2ad5fd-333e-4f77-a830-557b92f79b4b.jpg)
병민님 제 컴퓨터에서 마찬가지로 access_denied가 떠서 도움 요청 드립니다.

2021-08-25 05:04 UTC, lunayyko commented on projects/views.py
> +            bucket.Object('main_image_url').delete
S3에서 권한 수정하니까 됐습니다!!

2021-08-25 05:07 UTC, lunayyko commented on projects/views.py
> +                main_image_url = request.FILES.get('main_image_url')
넵 저장소에 저장하고 URL로 저장하는 것으로 바꾸었습니다

2021-08-25 09:23 UTC, lunayyko commented
<img width="782" alt="Screen Shot 2021-08-25 at 6 22 21 PM" src="https://user-images.githubusercontent.com/8315252/130764793-cc8383f1-4211-4798-a46f-edff8b47a7e4.png">
프로젝트 새로 업로드 하거나 수정/삭제하는데 8초나 걸리는데 혹시 어떻게 고칠 수 있을까요..?

2021-08-26 02:16 UTC, lunayyko commented
> <img alt="Screen Shot 2021-08-25 at 6 22 21 PM" width="782" src="https://user-images.githubusercontent.com/8315252/130764793-cc8383f1-4211-4798-a46f-edff8b47a7e4.png">
> 
> 프로젝트 새로 업로드 하거나 수정/삭제하는데 8초나 걸리는데 혹시 어떻게 고칠 수 있을까요..?

s3서버 오하이오에서 한국으로 바뀌니까 2초로 줄었습니다!!

2021-08-27 02:50 UTC, lunayyko commented
머지 솔브하고나서 풀하고 리베이스하면 컨플릭트가 계속 다시 생기네요..!

2021-08-27 02:55 UTC, lunayyko commented
> 머지 솔브하고나서 풀하고 리베이스하면 컨플릭트가 계속 다시 생기네요..!

git checkout main
git pull origin main
git checkout feature/project-upload
메인 오리진 풀 하고나서 리베이스하니까 없어졌습니다 ^_^*

2021-08-27 03:38 UTC, merged